server:
  port: 8080
javax:
  sql:
    DataSource:
      jpaDataSource:
        dataSourceClassName: com.mysql.cj.jdbc.MysqlDataSource
        dataSource:
          url: jdbc:mysql://localhost:3306/school
          user: yu71
          password: 53cret
